ARG BASEIMAGE=invalid_base_image
ARG BUILDPLATFORM

# BASEIMAGE
FROM ${BASEIMAGE} AS baseimage

# BUILDER
# Note: This stage runs on the build (and not the target) platform,
# because libguestfs spawns a mini-VM to create and write ext4 images and
# requires a native builder.
FROM --platform=${BUILDPLATFORM:-linux/amd64} quay.io/kubevirt/libguestfs-tools:20260516_6307741530 AS guestfs

ENV LIBGUESTFS_BACKEND=direct
ENV LIBGUESTFS_PATH=/usr/local/lib/guestfs/appliance
ENV LIBGUESTFS_TMPDIR=/tmp/guestfs
ENV HOME=/home/guestfs

# Extract the echoserver-tftp binary from baseimage into /echoserver-udp.
COPY --from=baseimage /usr/bin/echoserver-tftp /echoserver-udp/

# Create an ext4 disk image from /echoserver-udp.
RUN --mount=type=cache,mode=0755,uid=1001,gid=0,target=/home/guestfs \
    --mount=type=cache,mode=0755,uid=1001,gid=0,target=/tmp/guestfs \
    virt-make-fs /echoserver-udp --type=ext4 --format=qcow2 \
        --label=echoserver-udp /tmp/echoserver-udp.img

# CONTAINERDISK
# Provide the disk image in the format expected by KubeVirt.
FROM scratch
COPY --from=guestfs /tmp/echoserver-udp.img /disk/echoserver-udp.img
